/* Source wavelet estimation after Pratt (1999, Geophysics).
 * The impulse response is generated by the active modelling kernel, then the
 * weighted least-squares source estimate is formed trace by trace in frequency.
 */
#include <complex.h>
#include <fftw3.h>
#include <mpi.h>

#include "cstd.h"
#include "sim.h"
#include "acq.h"
#include "modelling.h"

void check_cfl(sim_t *sim);
void cpml_init(sim_t *sim);
void cpml_free(sim_t *sim);
void extend_model_init(sim_t *sim);
void extend_model_free(sim_t *sim);
void fdtd_init(sim_t *sim, int adj);
void fdtd_null(sim_t *sim, int adj);
void fdtd_free(sim_t *sim, int adj);
void write_vector(const char *name, const float *x, int n);

void do_invert_source(sim_t *sim, acq_t *acq)
/*< estimate the source time function from weighted observed data >*/
{
  int it, irec, ntpow2;
  float eps_factor, maxden;
  char *stffile;
  float *den, *num_real, *num_imag, *num_sum_real, *num_sum_imag, *den_sum;
  fftw_complex *num, *ft_dcal, *ft_dobs, *work;
  fftw_plan fft, ifft;

  if(!getparstring("stffile", &stffile)) err("mode=5 requires stffile=");
  if(!getparfloat("source_eps", &eps_factor)) eps_factor = 1.0e-4f;
  if(!(eps_factor>0.0f) || !isfinite(eps_factor))
    err("source_eps must be positive and finite");

  /* A unit impulse gives the receiver Green's functions for this source. */
  memset(sim->stf, 0, (size_t)sim->nt*sizeof(float));
  sim->stf[0] = 1.0f;
  check_cfl(sim);
  cpml_init(sim);
  extend_model_init(sim);
  fdtd_init(sim, 0);
  fdtd_null(sim, 0);
  modelling(sim, acq,
            sim->p, sim->vz, sim->vx, sim->vy, sim->memD1p,
            sim->memD2p, sim->memD3p, sim->memD1vz, sim->memD2vx,
            sim->memD3vy, sim->xi1, sim->xi2, sim->xi3, sim->vp,
            sim->rho, sim->qinv, sim->vpmod, sim->rhomod, sim->qinvmod,
            sim->kappa, sim->buz, sim->bux, sim->buy, sim->dcal);
  fdtd_free(sim, 0);
  extend_model_free(sim);
  cpml_free(sim);

  ntpow2 = 1;
  while(ntpow2<2*sim->nt) ntpow2 *= 2;
  den = alloc1float(ntpow2);
  num = (fftw_complex *)fftw_malloc((size_t)ntpow2*sizeof(*num));
  ft_dcal = (fftw_complex *)fftw_malloc((size_t)ntpow2*sizeof(*ft_dcal));
  ft_dobs = (fftw_complex *)fftw_malloc((size_t)ntpow2*sizeof(*ft_dobs));
  work = (fftw_complex *)fftw_malloc((size_t)ntpow2*sizeof(*work));
  if(num==NULL || ft_dcal==NULL || ft_dobs==NULL || work==NULL)
    err("cannot allocate source-inversion FFT arrays");
  fft = fftw_plan_dft_1d(ntpow2, work, work, FFTW_FORWARD, FFTW_ESTIMATE);
  ifft = fftw_plan_dft_1d(ntpow2, work, work, FFTW_BACKWARD, FFTW_ESTIMATE);
  if(fft==NULL || ifft==NULL) err("cannot create source-inversion FFT plans");

  for(it=0; it<ntpow2; it++){
    num[it] = 0.0;
    den[it] = 0.0f;
  }
  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++)
      work[it] = sim->dcal[irec][it]*acq->wdat[irec][it];
    for(it=sim->nt; it<ntpow2; it++) work[it] = 0.0;
    fftw_execute(fft);
    memcpy(ft_dcal, work, (size_t)ntpow2*sizeof(*ft_dcal));

    for(it=0; it<sim->nt; it++)
      work[it] = sim->dobs[irec][it]*acq->wdat[irec][it];
    for(it=sim->nt; it<ntpow2; it++) work[it] = 0.0;
    fftw_execute(fft);
    memcpy(ft_dobs, work, (size_t)ntpow2*sizeof(*ft_dobs));

    for(it=0; it<ntpow2; it++){
      num[it] += conj(ft_dcal[it])*ft_dobs[it];
      den[it] += (float)creal(conj(ft_dcal[it])*ft_dcal[it]);
    }
  }

  num_real = alloc1float(ntpow2);
  num_imag = alloc1float(ntpow2);
  num_sum_real = alloc1float(ntpow2);
  num_sum_imag = alloc1float(ntpow2);
  den_sum = alloc1float(ntpow2);
  for(it=0; it<ntpow2; it++){
    num_real[it] = (float)creal(num[it]);
    num_imag[it] = (float)cimag(num[it]);
  }
  if(sim->eachopt){
    memcpy(num_sum_real, num_real, (size_t)ntpow2*sizeof(float));
    memcpy(num_sum_imag, num_imag, (size_t)ntpow2*sizeof(float));
    memcpy(den_sum, den, (size_t)ntpow2*sizeof(float));
  }else{
    MPI_Allreduce(num_real, num_sum_real, ntpow2, MPI_FLOAT, MPI_SUM,
                  MPI_COMM_WORLD);
    MPI_Allreduce(num_imag, num_sum_imag, ntpow2, MPI_FLOAT, MPI_SUM,
                  MPI_COMM_WORLD);
    MPI_Allreduce(den, den_sum, ntpow2, MPI_FLOAT, MPI_SUM, MPI_COMM_WORLD);
  }
  maxden = 0.0f;
  for(it=0; it<ntpow2; it++){
    num[it] = num_sum_real[it]+I*num_sum_imag[it];
    den[it] = den_sum[it];
    maxden = MAX(maxden, fabsf(den[it]));
  }
  if(!(maxden>0.0f) || !isfinite(maxden))
    err("source inversion has zero or non-finite Green's-function energy");
  for(it=0; it<ntpow2; it++) work[it] = num[it]/(den[it]+eps_factor*maxden);
  fftw_execute(ifft);
  for(it=0; it<sim->nt; it++) sim->stf[it] = (float)creal(work[it])/ntpow2;

  if(sim->eachopt){
    char fname[PATH_MAX];
    snprintf(fname, sizeof(fname), "%s_%04d", stffile, acq->shot_idx[iproc]);
    write_vector(fname, sim->stf, sim->nt);
  }else if(iproc==0){
    write_vector(stffile, sim->stf, sim->nt);
  }

  free1float(den_sum);
  free1float(num_sum_imag);
  free1float(num_sum_real);
  free1float(num_imag);
  free1float(num_real);
  fftw_destroy_plan(ifft);
  fftw_destroy_plan(fft);
  fftw_free(work);
  fftw_free(ft_dobs);
  fftw_free(ft_dcal);
  fftw_free(num);
  free1float(den);
}
