/* Matrix-free data-domain linearized waveform inversion.
 *
 * The background wavefield and its linearization are both supplied by the
 * TApenade-generated modelling interfaces.  A CG solve is performed on the
 * normal equations
 *
 *        (J^T W^T W J) dm = J^T W^T W (dobs-d0),
 *
 * where d0 is the data generated by the background model.  modelling_d()
 * Applies J and modelling_b() Applies J^T to an explicit data seed.
 * Keeping the two operations here matrix-free avoids a second,
 * hand-maintained Born propagator that could drift from the production
 * viscoacoustic kernels.
 */
#include "cstd.h"
#include "sim.h"
#include "acq.h"
#include "modelling.h"

#include <mpi.h>

void check_cfl(sim_t *sim);
void cpml_init(sim_t *sim);
void cpml_free(sim_t *sim);
void extend_model_init(sim_t *sim);
void extend_model_free(sim_t *sim);
void fdtd_init(sim_t *sim, int adj);
void fdtd_null(sim_t *sim, int adj);
void fdtd_free(sim_t *sim, int adj);

typedef struct {
  float ***vpd, ***rhod, ***qinvd;
  float ***pd, ***vzd, ***vxd, ***vyd;
  float ***memD1pd, ***memD2pd, ***memD3pd;
  float ***memD1vzd, ***memD2vxd, ***memD3vyd;
  float ***xi1d, ***xi2d, ***xi3d;
  float ***vpmodd, ***rhomodd, ***qinvmodd;
  float ***kappad, ***buzd, ***buxd, ***buyd;
  float **dcald;

  float ***vpb, ***rhob, ***qinvb;
  float ***vpmodb, ***rhomodb, ***qinvmodb;
  float ***kappab, ***buzb, ***buxb, ***buyb;
  float **dcalb;
} workspace_t;

/* Allocate tangent, adjoint, and padded propagation buffers shared by LSM. */
static void lsm_alloc_workspace(sim_t *sim, acq_t *acq, workspace_t *w)
{
  memset(w, 0, sizeof(*w));

  w->vpd = alloc3float(sim->n1, sim->n2, sim->n3);
  w->rhod = alloc3float(sim->n1, sim->n2, sim->n3);
  w->qinvd = alloc3float(sim->n1, sim->n2, sim->n3);
  w->pd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->vzd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->vxd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->vyd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->memD1pd = alloc3float(2*sim->nb, sim->n2pad, sim->n3pad);
  w->memD2pd = alloc3float(sim->n1pad, 2*sim->nb, sim->n3pad);
  w->memD3pd = (sim->n3>1) ?
    alloc3float(sim->n1pad, sim->n2pad, 2*sim->nb) : alloc3float(1,1,1);
  w->memD1vzd = alloc3float(2*sim->nb, sim->n2pad, sim->n3pad);
  w->memD2vxd = alloc3float(sim->n1pad, 2*sim->nb, sim->n3pad);
  w->memD3vyd = (sim->n3>1) ?
    alloc3float(sim->n1pad, sim->n2pad, 2*sim->nb) : alloc3float(1,1,1);
  w->xi1d = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->xi2d = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->xi3d = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->vpmodd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->rhomodd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->qinvmodd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->kappad = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buzd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buxd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buyd = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->dcald = alloc2float(sim->nt, acq->nrec);

  w->vpb = alloc3float(sim->n1, sim->n2, sim->n3);
  w->rhob = alloc3float(sim->n1, sim->n2, sim->n3);
  w->qinvb = alloc3float(sim->n1, sim->n2, sim->n3);
  w->vpmodb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->rhomodb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->qinvmodb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->kappab = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buzb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buxb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->buyb = alloc3float(sim->n1pad, sim->n2pad, sim->n3pad);
  w->dcalb = alloc2float(sim->nt, acq->nrec);
}

/* Release every buffer allocated by lsm_alloc_workspace(). */
static void lsm_free_workspace(workspace_t *w)
{
  free2float(w->dcalb);
  free3float(w->buyb); free3float(w->buxb); free3float(w->buzb);
  free3float(w->kappab);
  free3float(w->qinvmodb); free3float(w->rhomodb); free3float(w->vpmodb);
  free3float(w->qinvb); free3float(w->rhob); free3float(w->vpb);

  free2float(w->dcald);
  free3float(w->buyd); free3float(w->buxd); free3float(w->buzd);
  free3float(w->kappad);
  free3float(w->qinvmodd); free3float(w->rhomodd); free3float(w->vpmodd);
  free3float(w->xi3d); free3float(w->xi2d); free3float(w->xi1d);
  free3float(w->memD3vyd); free3float(w->memD2vxd); free3float(w->memD1vzd);
  free3float(w->memD3pd); free3float(w->memD2pd); free3float(w->memD1pd);
  free3float(w->vyd); free3float(w->vxd); free3float(w->vzd); free3float(w->pd);
  free3float(w->qinvd); free3float(w->rhod); free3float(w->vpd);
}

/* x stores logarithmic perturbations (delta ln vp, delta ln Ip/rho, delta
 * ln Q^{-1}).  Convert to physical perturbations for the TLM.  For the
 * (ln vp, ln Ip) parameterization (family==2) the conversion couples the
 * two slabs: rhod receives a contribution from the vp slab because
 * delta rho = rho*(delta ln Ip - delta ln vp). */
static void lsm_set_direction(sim_t *sim, int family, int npar,
                              const int *idxpar, const float *x,
                              workspace_t *w)
{
  int i1, i2, i3, ipar, j;
  memset(w->vpd[0][0], 0, (size_t)sim->n123*sizeof(float));
  memset(w->rhod[0][0], 0, (size_t)sim->n123*sizeof(float));
  memset(w->qinvd[0][0], 0, (size_t)sim->n123*sizeof(float));

  for(ipar=0; ipar<npar; ipar++){
    for(i3=0; i3<sim->n3; i3++){
      for(i2=0; i2<sim->n2; i2++)
	for(i1=0; i1<sim->n1; i1++){
	  j = i1 + sim->n1*(i2 + sim->n2*(i3 + sim->n3*ipar));
	  if(idxpar[ipar]==1){
	    /* delta ln vp -> delta vp = vp * delta ln vp */
	    w->vpd[i3][i2][i1] += sim->vp[i3][i2][i1]*x[j];
	    if(family==2)
	      /* for (ln vp, ln Ip): delta rho gets -rho*delta ln vp */
	      w->rhod[i3][i2][i1] += -sim->rho[i3][i2][i1]*x[j];
	  }else if(idxpar[ipar]==2){
	    /* delta ln rho  (family==1) or delta ln Ip (family==2):
	     * both give delta rho = rho * delta ln X */
	    w->rhod[i3][i2][i1] += sim->rho[i3][i2][i1]*x[j];
	  }else if(idxpar[ipar]==3)
	    /* delta ln Q^{-1} -> delta qinv = qinv * delta ln Q^{-1} */
	    w->qinvd[i3][i2][i1] += sim->qinv[i3][i2][i1]*x[j];
	}
    }
  }
}

/* The TLM adjoint returns sensitivities with respect to the physical
 * perturbations (delta vp, delta rho, delta qinv).  Apply the chain rule
 * to obtain the gradient with respect to the logarithmic model parameters
 * (delta ln vp, delta ln rho/Ip, delta ln Q^{-1}). */
static void lsm_map_adjoint(sim_t *sim, int family, int npar,
                            const int *idxpar, const workspace_t *w,
                            float *g)
{
  int i1, i2, i3, ipar, j;
  for(ipar=0; ipar<npar; ipar++){
    for(i3=0; i3<sim->n3; i3++){
      for(i2=0; i2<sim->n2; i2++)
	for(i1=0; i1<sim->n1; i1++){
	  j = i1 + sim->n1*(i2 + sim->n2*(i3 + sim->n3*ipar));
	  if(idxpar[ipar]==1){
	    /* d/d(delta ln vp) = vp*d/d(delta vp) [+ rho correction] */
	    g[j] = sim->vp[i3][i2][i1]*w->vpb[i3][i2][i1];
	    if(family==2)
	      g[j] -= sim->rho[i3][i2][i1]*w->rhob[i3][i2][i1];
	  }else if(idxpar[ipar]==2){
	    /* d/d(delta ln rho) = rho*d/d(delta rho)
	     * d/d(delta ln Ip)  = rho*d/d(delta rho) as well */
	    g[j] = sim->rho[i3][i2][i1]*w->rhob[i3][i2][i1];
	  }else
	    /* d/d(delta ln Q^{-1}) = qinv*d/d(delta qinv) */
	    g[j] = sim->qinv[i3][i2][i1]*w->qinvb[i3][i2][i1];
	}
    }
  }
}

/* Apply the weighted Born operator WJ to a logarithmic model direction. 
 * TLM= Born modelling */
static void lsm_tlm(sim_t *sim, acq_t *acq, int family, int npar,
		    const int *idxpar, const float *x,
		    workspace_t *w, float **dout)
{
  int irec, it;

  lsm_set_direction(sim, family, npar, idxpar, x, w);
  fdtd_null(sim, 0);
  modelling_d(sim, acq,
              sim->p, w->pd, sim->vz, w->vzd, sim->vx, w->vxd,
              sim->vy, w->vyd, sim->memD1p, w->memD1pd,
              sim->memD2p, w->memD2pd, sim->memD3p, w->memD3pd,
              sim->memD1vz, w->memD1vzd, sim->memD2vx, w->memD2vxd,
              sim->memD3vy, w->memD3vyd, sim->xi1, w->xi1d,
              sim->xi2, w->xi2d, sim->xi3, w->xi3d, sim->vp, w->vpd,
              sim->rho, w->rhod, sim->qinv, w->qinvd, sim->vpmod,
              w->vpmodd, sim->rhomod, w->rhomodd, sim->qinvmod,
              w->qinvmodd, sim->kappa, w->kappad, sim->buz, w->buzd,
              sim->bux, w->buxd, sim->buy, w->buyd,
              sim->dcal, w->dcald);//w->dcald=J*x
  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      dout[irec][it] = acq->wdat[irec][it]*w->dcald[irec][it];//weight scattering data dout= WJx
    }
  }
  
}

/* Apply J^T W^T to an weighted data residual.  Seed the generated
 * data-output adjoint directly so a small residual is never rounded away by
 * subtracting it from the much larger background trace.
 * adjoint of Born modelling = demigration */
static void lsm_adj(sim_t *sim, acq_t *acq, float **residual,
		    int family, int npar,
		    const int *idxpar, workspace_t *w,
		    float *g, float *greduced)
{
  int irec, it;

  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      w->dcalb[irec][it] = acq->wdat[irec][it]*residual[irec][it];//weight again W^T residual
    }
  }

  memset(g, 0, (size_t)npar*sim->n123*sizeof(float));
  memset(w->vpb[0][0], 0, (size_t)sim->n123*sizeof(float));
  memset(w->rhob[0][0], 0, (size_t)sim->n123*sizeof(float));
  memset(w->qinvb[0][0], 0, (size_t)sim->n123*sizeof(float));
  fdtd_null(sim, 0);
  fdtd_null(sim, 1);
  modelling_b(sim, acq,
              sim->p, sim->pb, sim->vz, sim->vzb, sim->vx, sim->vxb,
              sim->vy, sim->vyb, sim->memD1p, sim->memD1pb,
              sim->memD2p, sim->memD2pb, sim->memD3p, sim->memD3pb,
              sim->memD1vz, sim->memD1vzb, sim->memD2vx, sim->memD2vxb,
              sim->memD3vy, sim->memD3vyb, sim->xi1, sim->xi1b,
              sim->xi2, sim->xi2b, sim->xi3, sim->xi3b, sim->vp, w->vpb,
              sim->rho, w->rhob, sim->qinv, w->qinvb, sim->vpmod,
              w->vpmodb, sim->rhomod, w->rhomodb, sim->qinvmod,
              w->qinvmodb, sim->kappa, w->kappab, sim->buz, w->buzb,
              sim->bux, w->buxb, sim->buy, w->buyb,
              sim->dcal, w->dcalb);// J^T W^T residual, map weighted data residual back to model space

  lsm_map_adjoint(sim, family, npar, idxpar, w, g);
  MPI_Allreduce(g, greduced, npar*sim->n123, MPI_FLOAT, MPI_SUM, MPI_COMM_WORLD);//stacking over all shots \sum_s
  memcpy(g, greduced, (size_t)npar*sim->n123*sizeof(float));
}


void write_vector(const char *name, const float *x, int n);
void append_vector(const char *name, const float *x, int n);

/* Check the TLM against finite differences and verify the WJ/WJ^T pair. */
static void lsm_adjoint_test(sim_t *sim, acq_t *acq)
{
  int family, npar, ipar;
  int *idxpar;
  workspace_t workspace, *w = &workspace;
  const float h = 1.0f;
  const double tiny = 1.0e-9;
  int i1, i2, i3, irec, it, j;

  if(!getparint("family", &family)) family = 1;
  if(family!=1 && family!=2) err("LSM family must be 1 (vp-rho) or 2 (vp-Ip)");
  if(!getparint("npar", &npar)) npar = 1;
  if(npar<1 || npar>3) err("LSM npar must be in [1,3]");
  idxpar = alloc1int(npar);
  if(countparval("idxpar")!=npar || !getparint("idxpar", idxpar))
    err("LSM requires idxpar= with %d values", npar);
  for(ipar=0; ipar<npar; ipar++){
    if(idxpar[ipar]<1 || idxpar[ipar]>3)
      err("LSM idxpar values must be 1 (vp), 2 (rho/Ip), or 3 (qinv)");
    if(idxpar[ipar]==3 && sim->nrelax==0)
      err("LSM idxpar=3 (qinv) requires nrelax=3");
  }
  lsm_alloc_workspace(sim, acq, w);
  check_cfl(sim);
  cpml_init(sim);
  extend_model_init(sim);
  fdtd_init(sim, 0);
  fdtd_init(sim, 1);

  int n = npar*sim->n123;
  double local_fd_error = 0.0, local_tlm_norm = 0.0;
  double fd_error, tlm_norm;
  double local_data_dot = 0.0, data_dot;
  double adjoint_dot = 0.0, adjoint_error;
  double tiny_expected, tiny_dot = 0.0, tiny_error;
  float *direction = alloc1float(n);
  float *gradient = alloc1float(n);
  float *greduced = alloc1float(n);
  float **tangent = alloc2float(sim->nt, acq->nrec);
  float **plus = alloc2float(sim->nt, acq->nrec);
  float **tiny_seed = alloc2float(sim->nt, acq->nrec);

  for(ipar=0; ipar<npar; ipar++){
    for(i3=0; i3<sim->n3; i3++){
      for(i2=0; i2<sim->n2; i2++)
	for(i1=0; i1<sim->n1; i1++){
	  int pattern = (i1 + 3*i2 + 5*i3 + 7*ipar)%11;
	  j = i1 + sim->n1*(i2 + sim->n2*(i3 + sim->n3*ipar));
	  direction[j] = 1.0e-3f*(0.5f + 0.1f*(float)pattern);
	}
    }
  }

  if(iproc==0) printf("---- LSM TLM/adjoint consistency test ----\n");
  lsm_tlm(sim, acq, family, npar, idxpar, direction, w, tangent);

  /* Compare WJ dm with a centered difference of the nonlinear modelling
   * operator using the identical physical perturbation. */
  for(i3=0; i3<sim->n3; i3++){
    for(i2=0; i2<sim->n2; i2++){
      for(i1=0; i1<sim->n1; i1++){
	sim->vp[i3][i2][i1] += h*w->vpd[i3][i2][i1];
	sim->rho[i3][i2][i1] += h*w->rhod[i3][i2][i1];
	sim->qinv[i3][i2][i1] += h*w->qinvd[i3][i2][i1];
      }
    }
  }
  fdtd_null(sim, 0);
  modelling(sim, acq,
            sim->p, sim->vz, sim->vx, sim->vy, sim->memD1p,
            sim->memD2p, sim->memD3p, sim->memD1vz, sim->memD2vx,
            sim->memD3vy, sim->xi1, sim->xi2, sim->xi3, sim->vp,
            sim->rho, sim->qinv, sim->vpmod, sim->rhomod, sim->qinvmod,
            sim->kappa, sim->buz, sim->bux, sim->buy, sim->dcal);
  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      plus[irec][it] = acq->wdat[irec][it]*sim->dcal[irec][it];
    }
  }
  for(i3=0; i3<sim->n3; i3++){
    for(i2=0; i2<sim->n2; i2++){
      for(i1=0; i1<sim->n1; i1++){
	sim->vp[i3][i2][i1] -= 2.0f*h*w->vpd[i3][i2][i1];
	sim->rho[i3][i2][i1] -= 2.0f*h*w->rhod[i3][i2][i1];
	sim->qinv[i3][i2][i1] -= 2.0f*h*w->qinvd[i3][i2][i1];
      }
    }
  }
  fdtd_null(sim, 0);
  modelling(sim, acq,
            sim->p, sim->vz, sim->vx, sim->vy, sim->memD1p,
            sim->memD2p, sim->memD3p, sim->memD1vz, sim->memD2vx,
            sim->memD3vy, sim->xi1, sim->xi2, sim->xi3, sim->vp,
            sim->rho, sim->qinv, sim->vpmod, sim->rhomod, sim->qinvmod,
            sim->kappa, sim->buz, sim->bux, sim->buy, sim->dcal);
  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      double minus = (double)acq->wdat[irec][it]*sim->dcal[irec][it];
      double fd = ((double)plus[irec][it]-minus)/(2.0*(double)h);
      double diff = fd-(double)tangent[irec][it];
      local_fd_error += diff*diff;
      local_tlm_norm += (double)tangent[irec][it]*tangent[irec][it];
    }
  }
  for(i3=0; i3<sim->n3; i3++){
    for(i2=0; i2<sim->n2; i2++){
      for(i1=0; i1<sim->n1; i1++){
	sim->vp[i3][i2][i1] += h*w->vpd[i3][i2][i1];
	sim->rho[i3][i2][i1] += h*w->rhod[i3][i2][i1];
	sim->qinv[i3][i2][i1] += h*w->qinvd[i3][i2][i1];
      }
    }
  }
  MPI_Allreduce(&local_fd_error, &fd_error, 1, MPI_DOUBLE, MPI_SUM,
                MPI_COMM_WORLD);
  MPI_Allreduce(&local_tlm_norm, &tlm_norm, 1, MPI_DOUBLE, MPI_SUM,
                MPI_COMM_WORLD);
  fd_error = sqrt(fd_error/MAX(1.0e-30, tlm_norm));

  /* lsm_tlm returns WJ dm and lsm_adj applies J^T W^T. */
  lsm_adj(sim, acq, tangent, family, npar, idxpar, w, gradient, greduced);
  for(j=0; j<n; j++) adjoint_dot += (double)direction[j]*gradient[j];
  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      local_data_dot += (double)tangent[irec][it]*tangent[irec][it];
    }
  }
  MPI_Allreduce(&local_data_dot, &data_dot, 1, MPI_DOUBLE, MPI_SUM,
                MPI_COMM_WORLD);
  adjoint_error = fabs(adjoint_dot-data_dot)
    / MAX(1.0e-30, MAX(fabs(adjoint_dot), fabs(data_dot)));

  for(irec=0; irec<acq->nrec; irec++){
    for(it=0; it<sim->nt; it++){
      tiny_seed[irec][it] = (float)(tiny*(double)tangent[irec][it]);
    }
  }
  lsm_adj(sim, acq, tiny_seed, family, npar, idxpar, w, gradient, greduced);
  for(j=0; j<n; j++)
    tiny_dot += tiny*(double)direction[j]*gradient[j];
  tiny_expected = tiny*tiny*data_dot;
  tiny_error = fabs(tiny_dot-tiny_expected)
    / MAX(1.0e-35, MAX(fabs(tiny_dot), fabs(tiny_expected)));

  if(iproc==0){
    printf("TLM-vs-FD relative L2 error=%g\n", fd_error);
    printf("adjoint test: <WJd,WJd>=%g <d,J^TW^TWJd>=%g relative-error=%g\n",
           data_dot, adjoint_dot, adjoint_error);
    printf("tiny normal test: expected=%g pAp=%g relative-error=%g\n",
           tiny_expected, tiny_dot, tiny_error);
  }

  free2float(tiny_seed);
  free2float(plus);
  free2float(tangent);
  free1float(greduced);
  free1float(gradient);
  free1float(direction);
  fdtd_free(sim, 1);
  fdtd_free(sim, 0);
  extend_model_free(sim);
  cpml_free(sim);
  lsm_free_workspace(w);
  free1int(idxpar);

  if(!(tlm_norm>0.0) || fd_error>5.0e-3 || adjoint_error>5.0e-5
     || !(tiny_dot>0.0) || tiny_error>5.0e-5)
    err("LSM TLM/adjoint consistency test failed");
}

/* Solve the unregularized normal equations with matrix-free CG. */
static void lsm_solve_cg(sim_t *sim, acq_t *acq)
/*< perform data-domain linearized waveform inversion with CG >*/
{
  int npar, n, niter, iter, ipar, j, it;
  int family, output_dcal;
  int *idxpar;
  float tol;
  float *b, *x, *r, *p, *Ap, *greduced, **dsyn, **dcal_iter = NULL;
  workspace_t w;
  double rr, rr0, rr_new, pAp, alpha, beta, tmp, fcost, fcost0;
  FILE *fp;
  
  if(!getparint("family", &family)) family = 1;
  if(family!=1 && family!=2) err("LSM family must be 1 (vp-rho) or 2 (vp-Ip)");
  if(!getparint("npar", &npar)) npar = 1;
  if(npar<1 || npar>3) err("LSM npar must be in [1,3]");
  idxpar = alloc1int(npar);
  if(countparval("idxpar")!=npar || !getparint("idxpar", idxpar))
    err("LSM requires idxpar= with %d values", npar);
  for(ipar=0; ipar<npar; ipar++){
    if(idxpar[ipar]<1 || idxpar[ipar]>3)
      err("LSM idxpar values must be 1 (vp), 2 (rho/Ip), or 3 (qinv)");
    if(idxpar[ipar]==3 && sim->nrelax==0)
      err("LSM idxpar=3 (qinv) requires nrelax=3");
  }
  if(!getparint("niter", &niter)) niter = 30;
  if(niter<0) err("LSM niter must be nonnegative");
  if(!getparfloat("tol_cg", &tol)) tol = 1.0e-3f;
  if(!(tol>0.0f)) err("LSM tol_cg must be positive");
  if(!getparint("output_dcal", &output_dcal)) output_dcal = 0;

  n = npar*sim->n123;
  lsm_alloc_workspace(sim, acq, &w);

  check_cfl(sim);
  cpml_init(sim);
  extend_model_init(sim);
  fdtd_init(sim, 0);
  fdtd_init(sim, 1);

  b = alloc1float(n);
  x = alloc1float(n);
  r = alloc1float(n);
  p = alloc1float(n);
  Ap = alloc1float(n);
  greduced = alloc1float(n);
  memset(x, 0, (size_t)n*sizeof(float));
  dsyn = alloc2float(sim->nt, acq->nrec);
  if(output_dcal) dcal_iter = alloc2float(sim->nt, acq->nrec);

  /* Build d0 once. The original observed data remain in sim->dobs; the LSM
   * reverse sweep receives its data-space seed separately in dcalb. */
  if(iproc==0) printf("---- LSM background modelling (d0) ----\n");
  fdtd_null(sim, 0);
  fdtd_null(sim, 1);
  modelling(sim, acq,
            sim->p, sim->vz, sim->vx, sim->vy, sim->memD1p,
            sim->memD2p, sim->memD3p, sim->memD1vz, sim->memD2vx,
            sim->memD3vy, sim->xi1, sim->xi2, sim->xi3, sim->vp,
            sim->rho, sim->qinv, sim->vpmod, sim->rhomod, sim->qinvmod,
            sim->kappa, sim->buz, sim->bux, sim->buy, sim->dcal);
  if(output_dcal){//output background modelled data immediately
    char fname[sizeof("d0_0000")];
    sprintf(fname, "d0_%04d", acq->shot_idx[iproc]);
    write_vector(fname, sim->dcal[0], sim->nt*acq->nrec);
    memcpy(dcal_iter[0], sim->dcal[0], (size_t)sim->nt*acq->nrec*sizeof(float));
  }
  if(iproc==0) printf("background field modelling completed\n");
  fcost = 0;
  for(j=0; j<acq->nrec; j++){
    for(it=0; it<sim->nt; it++){
      sim->dres[j][it] = (sim->dobs[j][it] - sim->dcal[j][it]);//reflection data 
      sim->dres[j][it] *= acq->wdat[j][it];//W \delta d
      fcost += sim->dres[j][it]*sim->dres[j][it];
    }
  }
  MPI_Allreduce(&fcost, &fcost0, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
  fcost0 *= 0.5;
  fcost = fcost0;
  
  lsm_adj(sim, acq, sim->dres, family, npar, idxpar, &w, b, greduced);//(WL)^T [W \delta d]
  if(iproc==0){
    write_vector("image_rtm", b, n);
    printf("Right hand side of LSM (RTM image) computed\n");
  }
  rr = 0.;
  for(j=0; j<n; j++){
    r[j] = b[j];
    p[j] = r[j];
    rr += (double)r[j]*(double)r[j];
  }
  rr0 = rr;
  if(iproc==0) {
    fp=fopen("iterate.txt","w");
    if(fp==NULL) err("cannot open iterate.txt for appending");
    fprintf(fp,"iter    fk       fk/f0\n");
    fclose(fp);
  }


  if(!(rr0>=0.0) || !isfinite(rr0))
    err("LSM initial residual norm is not finite");
  if(iproc==0)
    printf("LSM initial residual norm=%e\n", sqrt(rr0));
  if(iproc==0) write_vector("param_iter", x, 0);

  for(iter=0; iter<niter && rr0>0.0 && sqrt(rr)>tol*sqrt(rr0); iter++){
    if(iproc==0){
      printf("---- LSM CG iter=%d, fcost=%e ----\n", iter, fcost);

      fp=fopen("iterate.txt","a");
      fprintf(fp,"%d    %e       %e\n", iter, fcost, fcost/fcost0);
      fclose(fp);
    }
    lsm_tlm(sim, acq, family, npar, idxpar, p, &w, dsyn);// dsyn= WLp
    if(iproc==0) printf("Born modelling completed\n");
    lsm_adj(sim, acq, dsyn, family, npar, idxpar, &w, Ap, greduced);
    if(iproc==0) printf("migration completed\n");
    tmp = 0;
    for(j=0; j<acq->nrec; j++){
      for(it=0; it<sim->nt; it++){
	tmp += (double)dsyn[j][it]*(double)dsyn[j][it]; //pAp=<p,(WL)^T WLp>=<WLp, WLp>=|dsyn|^2
      }
    }
    MPI_Allreduce(&tmp, &pAp, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
    if(!(pAp>0.0) || !isfinite(pAp))
      err("LSM CG breakdown: p^T A p is not positive and finite");
    alpha = rr/pAp;
    if(!isfinite(alpha)) err("LSM CG breakdown: step length is not finite");
    rr_new = 0;
    fcost = 0;
    for(j=0; j<n; j++){
      x[j] += (float)alpha*p[j];
      r[j] -= (float)alpha*Ap[j];
      rr_new += (double)r[j]*(double)r[j];
      fcost += x[j]*(r[j] + b[j]);
    }    
    fcost = -0.5*fcost + fcost0;
    if(output_dcal){
      /* w.dcald is the unweighted Jp from the TLM just evaluated above. */
      for(j=0; j<acq->nrec; j++){
	for(it=0; it<sim->nt; it++){
	  dcal_iter[j][it] += (float)alpha*w.dcald[j][it];
	}
      }
      //output synthetic data at each iteration
      char fname[sizeof("dcal_0000")];
      sprintf(fname, "dcal_%04d", acq->shot_idx[iproc]);
      write_vector(fname, dcal_iter[0], sim->nt*acq->nrec);
    }
    if(!(rr_new>=0.0) || !isfinite(rr_new))
      err("LSM CG breakdown: residual norm is not finite");
    beta = rr_new/rr;
    if(!isfinite(beta)) err("LSM CG breakdown: beta is not finite");
    for(j=0; j<n; j++) p[j] = r[j] + (float)beta*p[j];
    rr = rr_new;
    if(iproc==0){
      write_vector("param_final", x, n);
      append_vector("param_iter", x, n);
      printf("LSM finished: relative residual=%e\n", sqrt(rr/rr0));
    }

  }
  
  fdtd_free(sim, 1);
  fdtd_free(sim, 0);
  extend_model_free(sim);
  cpml_free(sim);
  lsm_free_workspace(&w);
  free1float(greduced);
  free1float(Ap);
  free1float(p);
  free1float(r);
  free1float(x);
  free1float(b);
  if(output_dcal) free2float(dcal_iter);
  free2float(dsyn);
  free1int(idxpar);
}

/* Solve the L1-penalized objective with FISTA soft thresholding. */
static void lsm_solve_fista(sim_t *sim, acq_t *acq)
/*< perform sparse data-domain linearized waveform inversion with FISTA >*/
{
  int npar, n, niter, iter, ipar, j, it, power_iter;
  int family;
  int *idxpar;
  float tol, lambda, step, t, tnew;
  float *b, *x, *xnext, *y, *g, *power, *greduced;
  float **dsyn, **dcal0;
  workspace_t w;
  double bnorm, gnorm, eig, change, xnorm, local_cost, data_cost, l1_cost;

  if(!getparint("family", &family)) family = 1;
  if(family!=1 && family!=2) err("LSM family must be 1 (vp-rho) or 2 (vp-Ip)");
  if(!getparint("npar", &npar)) npar = 1;
  if(npar<1 || npar>3) err("LSM npar must be in [1,3]");
  idxpar = alloc1int(npar);
  if(countparval("idxpar")!=npar || !getparint("idxpar", idxpar))
    err("LSM requires idxpar= with %d values", npar);
  for(ipar=0; ipar<npar; ipar++){
    if(idxpar[ipar]<1 || idxpar[ipar]>3)
      err("LSM idxpar values must be 1 (vp), 2 (rho/Ip), or 3 (qinv)");
    if(idxpar[ipar]==3 && sim->nrelax==0)
      err("LSM idxpar=3 (qinv) requires nrelax=3");
  }
  if(!getparint("niter", &niter)) niter = 100;
  if(niter<0) err("LSM niter must be nonnegative");
  if(!getparfloat("tol_l1", &tol)) tol = 1.0e-4f;
  if(!(tol>0.0f)) err("LSM tol_l1 must be positive");
  if(!getparint("power_iter", &power_iter)) power_iter = 6;
  if(power_iter<1) err("LSM power_iter must be positive");

  n = npar*sim->n123;
  lsm_alloc_workspace(sim, acq, &w);
  check_cfl(sim);
  cpml_init(sim);
  extend_model_init(sim);
  fdtd_init(sim, 0);
  fdtd_init(sim, 1);

  b = alloc1float(n);
  x = alloc1float(n);
  xnext = alloc1float(n);
  y = alloc1float(n);
  g = alloc1float(n);
  power = alloc1float(n);
  greduced = alloc1float(n);
  dsyn = alloc2float(sim->nt, acq->nrec);
  dcal0 = alloc2float(sim->nt, acq->nrec);
  memset(x, 0, (size_t)n*sizeof(float));
  memset(y, 0, (size_t)n*sizeof(float));

  if(iproc==0) printf("---- Sparse LSM background modelling (d0) ----\n");
  fdtd_null(sim, 0);
  fdtd_null(sim, 1);
  modelling(sim, acq,
            sim->p, sim->vz, sim->vx, sim->vy, sim->memD1p,
            sim->memD2p, sim->memD3p, sim->memD1vz, sim->memD2vx,
            sim->memD3vy, sim->xi1, sim->xi2, sim->xi3, sim->vp,
            sim->rho, sim->qinv, sim->vpmod, sim->rhomod, sim->qinvmod,
            sim->kappa, sim->buz, sim->bux, sim->buy, sim->dcal);
  {
    char fname[sizeof("d0_0000")];
    sprintf(fname, "d0_%04d", acq->shot_idx[iproc]);
    write_vector(fname, sim->dcal[0], sim->nt*acq->nrec);
  }
  memcpy(dcal0[0], sim->dcal[0],
         (size_t)sim->nt*acq->nrec*sizeof(float));
  for(j=0; j<acq->nrec; j++){
    for(it=0; it<sim->nt; it++)
      sim->dres[j][it] = acq->wdat[j][it]
        *(sim->dobs[j][it]-sim->dcal[j][it]);
  }
  lsm_adj(sim, acq, sim->dres, family, npar, idxpar, &w, b, greduced);

  bnorm = 0.0;
  lambda = 0.0f;
  for(j=0; j<n; j++){
    bnorm += (double)b[j]*(double)b[j];
    lambda = MAX(lambda, fabsf(b[j]));
  }
  bnorm = sqrt(bnorm);
  if(!(bnorm>0.0) || !isfinite(bnorm))
    err("Sparse LSM initial adjoint image norm is not positive and finite");
  if(!getparfloat("lambda_l1", &lambda)) lambda *= 1.0e-2f;
  if(lambda<0.0f || !isfinite(lambda))
    err("LSM lambda_l1 must be nonnegative and finite");

  for(j=0; j<n; j++) power[j] = b[j]/(float)bnorm;
  eig = 0.0;
  for(ipar=0; ipar<power_iter; ipar++){
    lsm_tlm(sim, acq, family, npar, idxpar, power, &w, dsyn);
    lsm_adj(sim, acq, dsyn, family, npar, idxpar, &w, g, greduced);
    eig = 0.0;
    gnorm = 0.0;
    for(j=0; j<n; j++){
      eig += (double)power[j]*(double)g[j];
      gnorm += (double)g[j]*(double)g[j];
    }
    gnorm = sqrt(gnorm);
    if(!(gnorm>0.0) || !isfinite(gnorm))
      err("Sparse LSM normal operator norm is not positive and finite");
    for(j=0; j<n; j++) power[j] = g[j]/(float)gnorm;
  }
  if(!(eig>0.0) || !isfinite(eig))
    err("Sparse LSM Lipschitz estimate is not positive and finite");
  step = 0.8f/(float)eig;
  t = 1.0f;
  if(iproc==0){
    write_vector("param_l1_iter", x, 0);
    printf("Sparse LSM: lambda_l1=%e step=%e\n", lambda, step);
  }

  for(iter=0; iter<niter; iter++){
    lsm_tlm(sim, acq, family, npar, idxpar, y, &w, dsyn);
    lsm_adj(sim, acq, dsyn, family, npar, idxpar, &w, g, greduced);
    local_cost = 0.0;
    for(j=0; j<acq->nrec; j++){
      for(it=0; it<sim->nt; it++){
        double residual = (double)dsyn[j][it]-(double)sim->dres[j][it];
        local_cost += residual*residual;
      }
    }
    MPI_Allreduce(&local_cost, &data_cost, 1, MPI_DOUBLE, MPI_SUM, MPI_COMM_WORLD);
    change = 0.0;
    xnorm = 0.0;
    l1_cost = 0.0;
    for(j=0; j<n; j++){
      float value = y[j]-step*(g[j]-b[j]);
      //soft-thresholding
      if(value>step*lambda) xnext[j] = value-step*lambda;
      else if(value<-step*lambda) xnext[j] = value+step*lambda;
      else xnext[j] = 0.0f;
      change += (double)(xnext[j]-x[j])*(double)(xnext[j]-x[j]);
      xnorm += (double)xnext[j]*(double)xnext[j];
      l1_cost += fabs((double)xnext[j]);
    }
    tnew = 0.5f*(1.0f+sqrtf(1.0f+4.0f*t*t));
    for(j=0; j<n; j++){
      y[j] = xnext[j]+((t-1.0f)/tnew)*(xnext[j]-x[j]);
      x[j] = xnext[j];
    }
    t = tnew;
    if(iproc==0){
      write_vector("param_l1_final", x, n);
      append_vector("param_l1_iter", x, n);
      printf("Sparse LSM iter=%d objective=%e relative update=%e\n", iter,
             0.5*data_cost+(double)lambda*l1_cost,
             sqrt(change/MAX(1.0, xnorm)));
    }
    if(sqrt(change)<=tol*MAX(1.0, sqrt(xnorm))) break;
  }
  
  lsm_tlm(sim, acq, family, npar, idxpar, x, &w, dsyn);
  for(j=0; j<acq->nrec; j++){
    for(it=0; it<sim->nt; it++)
      dsyn[j][it] = dcal0[j][it]+w.dcald[j][it];
  }
  {
    char fname[sizeof("dcal_l1_final_0000")];
    sprintf(fname, "dcal_l1_final_%04d", acq->shot_idx[iproc]);
    write_vector(fname, dsyn[0], sim->nt*acq->nrec);
  }

  fdtd_free(sim, 1);
  fdtd_free(sim, 0);
  extend_model_free(sim);
  cpml_free(sim);
  lsm_free_workspace(&w);
  free2float(dcal0);
  free2float(dsyn);
  free1float(greduced);
  free1float(power);
  free1float(g);
  free1float(y);
  free1float(xnext);
  free1float(x);
  free1float(b);
  free1int(idxpar);
}

void do_lsm(sim_t *sim, acq_t *acq)
/*< perform data-domain linearized waveform inversion >*/
{
  int lsm_method, test_tlm_adjoint;

  if(!getparint("test_tlm_adjoint", &test_tlm_adjoint)) test_tlm_adjoint = 0;
  if(test_tlm_adjoint!=0 && test_tlm_adjoint!=1) err("test_tlm_adjoint must be 0 or 1");
  if(test_tlm_adjoint==1){
    lsm_adjoint_test(sim, acq);
    return;
  }

  /* Keep CG as the legacy default; both solvers use the same TLM/adjoint
   * interfaces but impose different regularization models. */
  if(!getparint("lsm_method", &lsm_method)) lsm_method = 1;
  if(lsm_method==1)
    /* Unregularized least-squares solve of the normal equations. */
    lsm_solve_cg(sim, acq);
  else if(lsm_method==2)
    /* Proximal FISTA solve with an L1 penalty on the perturbation vector. */
    lsm_solve_fista(sim, acq);
  else
    err("lsm_method must be 1 (CG) or 2 (FISTA L1)");
}

void lsm_hessian_vector(sim_t *sim, acq_t *acq, int family, int npar,
                        const int *idxpar, const float *v, float *Hv)
/*< apply the weighted Gauss-Newton Hessian J^T W^T W J >*/
{
  int n = npar*sim->n123;
  float *greduced = alloc1float(n);
  float **dsyn = alloc2float(sim->nt, acq->nrec);
  workspace_t w;

  lsm_alloc_workspace(sim, acq, &w);
  check_cfl(sim);
  cpml_init(sim);
  extend_model_init(sim);
  fdtd_init(sim, 0);
  fdtd_init(sim, 1);
  lsm_tlm(sim, acq, family, npar, idxpar, v, &w, dsyn);
  lsm_adj(sim, acq, dsyn, family, npar, idxpar, &w, Hv, greduced);
  fdtd_free(sim, 1);
  fdtd_free(sim, 0);
  extend_model_free(sim);
  cpml_free(sim);
  lsm_free_workspace(&w);
  free2float(dsyn);
  free1float(greduced);
}
